- hosts: ubuntu
  tasks:
  - name: Install apache httpd  (state=present is optional)
    apt:
      name: apache2
      state: present
      update_cache: yes

  - name: Install unzip
    apt:
      name: unzip
      state: latest
      update_cache: yes    

  - name: Unarchive a file that needs to be downloaded (added in 2.0)
    unarchive:
      src: https://www.free-css.com/assets/files/free-css-templates/download/page283/milina.zip
      dest: /tmp/
      remote_src: yes    

  - name: Move template file to /var/www/html/
    shell: "mv /tmp/milina-html/*  /var/www/html/"    